services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    command: redis-server
    ports:
      - 6379:6379

  celery_worker:
    build: .
    command: celery -A config worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - redis
      
volumes:
  postgres_data: